---
- name: Install redis
  tags:
    - system
    - pkgs
  openbsd_pkg:
    name: "{{ item }}"
    state: installed
  with_items:
    - redis
    - ruby24-redis
    - ruby24-redis-namespace

- name: enable redis
  service:
    name: redis
    enabled: yes
    state: started

